AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Globals:
    Function:
        Timeout: 40

Resources:
  LocalApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: "2.0"
        paths:
          "/":
            get:
              x-amazon-apigateway-integration:
                httpMethod: "GET"
                type: aws_proxy
                #uri: "https://hopefullyIrellevant.com"
        x-amazon-apigateway-binary-media-types:
          - "*/*"

  Excel:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.6
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LocalApi
            Path: /
            Method: get
